Feature: Human-Readable SBOM Report via CycloneDX/Sunshine
  As a DevSecOps Engineer
  I want an optional, human-readable HTML report of the SBOM
  So that people who aren't comfortable reading raw JSON can review
  components, dependencies, and licenses at a glance.

  Scenario: Report Generated By Default
    Given the action runs with no "human-readable-report" input given
    When the SBOM has been generated and enriched
    Then a "Generate Human-Readable SBOM Report" step runs
    And its output is uploaded as a workflow artifact named "sbom-report"

  Scenario: Report Generation Can Be Disabled
    Given the action runs with "human-readable-report" set to "false"
    When the workflow steps are inspected
    Then the "Install Sunshine" step does not run
    And the "Generate Human-Readable SBOM Report" step does not run
    And the "Upload Human-Readable SBOM Report" step does not run
