#!/usr/bin/env bats
# Acceptance tests for features/human-readable-reporting.feature.
#
# As with the self-isolation tests, these parse the real action.yml
# rather than running Sunshine for real (it needs network access this
# sandbox's policy doesn't grant to arbitrary hosts). They assert on
# the declared default and gating condition, not on a live run.

setup() {
  ACTION_YML="$(cd "$(dirname "$BATS_TEST_FILENAME")/../.." && pwd)/action.yml"
}

get_doc() {
  python3 -c "import yaml; print(yaml.dump(yaml.safe_load(open('$ACTION_YML'))))"
}

@test "Scenario: Report Generated By Default" {
  doc=$(get_doc)

  # the human-readable-report input defaults to 'true'
  default=$(python3 - "$ACTION_YML" <<'EOF'
import sys, yaml
doc = yaml.safe_load(open(sys.argv[1]))
print(doc["inputs"]["human-readable-report"]["default"])
EOF
)
  [ "$default" = "true" ]

  # all three steps exist and are gated on that same input
  for step_name in "Install Sunshine" "Generate Human-Readable SBOM Report" "Upload Human-Readable SBOM Report"; do
    condition=$(python3 - "$ACTION_YML" "$step_name" <<'EOF'
import sys, yaml
doc = yaml.safe_load(open(sys.argv[1]))
name = sys.argv[2]
for step in doc["runs"]["steps"]:
    if step.get("name") == name:
        print(step.get("if", ""))
        sys.exit(0)
sys.exit(1)
EOF
)
    [ "$condition" = "inputs.human-readable-report == 'true'" ]
  done

  # the upload step uses actions/upload-artifact and names the artifact
  # exactly "sbom-report" (parsed field compared exactly, not a substring
  # match, so e.g. "sbom-report-extra" would not slip past this)
  artifact_name=$(python3 - "$ACTION_YML" <<'EOF'
import sys, yaml
doc = yaml.safe_load(open(sys.argv[1]))
for step in doc["runs"]["steps"]:
    if step.get("name") == "Upload Human-Readable SBOM Report":
        print(step.get("with", {}).get("name", ""))
EOF
)
  uses_value=$(python3 - "$ACTION_YML" <<'EOF'
import sys, yaml
doc = yaml.safe_load(open(sys.argv[1]))
for step in doc["runs"]["steps"]:
    if step.get("name") == "Upload Human-Readable SBOM Report":
        print(step.get("uses", ""))
EOF
)
  [ "$artifact_name" = "sbom-report" ]
  [[ "$uses_value" == actions/upload-artifact@* ]]
}

@test "Scenario: Report Generation Can Be Disabled" {
  # all three steps are gated by the same input, so setting it to 'false'
  # skips all three (GitHub Actions evaluates "if:" against the actual
  # input value at runtime; here we confirm the gate exists and is the
  # input, not e.g. hardcoded 'true' or a typo'd input name)
  for step_name in "Install Sunshine" "Generate Human-Readable SBOM Report" "Upload Human-Readable SBOM Report"; do
    condition=$(python3 - "$ACTION_YML" "$step_name" <<'EOF'
import sys, yaml
doc = yaml.safe_load(open(sys.argv[1]))
name = sys.argv[2]
for step in doc["runs"]["steps"]:
    if step.get("name") == name:
        print(step.get("if", ""))
        sys.exit(0)
sys.exit(1)
EOF
)
    [[ "$condition" == *"inputs.human-readable-report"* ]]
  done
}
